06-task
js-tasks-ru/vue-20230905_3410914 pull request #6
Opened 2023-10-06 11:57 UTC by borshchevsky

Только 4 задачи.

2023-10-06 11:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-06 19:11 UTC, ShGKme requested changes

2023-10-06 19:11 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </component>
`v-bind="$attrs"` здесь лишний. Все параметры уже сами наследуются, так как `<component>` - корневой элемент, а наследование не отключено. В итоге все параметры и обработчики событий наследуются два раза. Один раз автоматически (так как не отключено через `inheritAttrs: false`), один раз вручную с `v-bind="$attrs"`

2023-10-06 19:11 UTC, ShGKme commented on 06-wrappers/05-UiImageUploader/App.vue
Не могу зачесть удаление задачи за её решение...

2023-10-09 07:52 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-09 07:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-09 07:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-09 07:59 UTC, borshchevsky commented on 06-wrappers/05-UiImageUploader/App.vue
Вернул задачи.

2023-10-09 07:59 UTC, borshchevsky commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </component>
Убрал.

2023-10-09 17:25 UTC, ShGKme reviewed
Исправления приняты, но не все добавленные задачи решены

2023-10-10 08:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-10 08:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-10 09:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-10 11:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-10 13:56 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-10 16:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-11 06:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-11 06:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-11 06:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-11 10:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-11 12:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-11 12:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-11 12:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-11 13:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +      </div>
В `Vue` нельзя устанавливать `v-for` и `v-if` на один узел, так как не очевиден приоритет их применения. Условие на проверку того,  не пустое ли перебирается значение - не нужно, так как если программа будет пуста, то и итераций цикл сделает 0.

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +      </div>
При этом оборачивание в див здесь лишнее, можно устанавливать цикл сразу на повторяющийся компонент.

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +  }
С разделением на отдельные свойства код получается сложноватым...

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +  }
Можно работать сразу с `localAgendaItem`

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  }
Устанавливать значение в `mounted` - поздно. `mounted` срабатывает, когда компонент уже срендерился. Это означает, что изначально компонент всегда рендерится, ещё не имея актуального `counter`. С проверкой `count || counter` это не приводит к проблеме, но в общем случае может быть проблемой.

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  }
Входной параметр здесь всегда имеет приоритет над локальным состоянием, и если родитель передаст начальное значение счётчика не 0, то без помощи родителя на локальном `counter` компонент уже работать не сможет.

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  }
Нужно всегда выводить локальное состояние, которое синхронизируется с родителем

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
Поиск элемента для замены через `id` - не совсем корректный подход для обновления.

Форма редактирования пункта программы может потенциально менять `id`, например, если будет сразу сохранять его на сервере.

Нам не нужно искать, какой именно пункт программы обновился. Если 3-я форма редактирования пункта программы (3-его пункта программы) сообщила, что пункт программы обновился -- значит обновился 3-ий пункт программы. Его не нужно искать, мы знаем, что он 3-ий.

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +      </div>
Оборачивание в див здесь тоже лишнее

2023-10-11 18:01 UTC, ShGKme commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +  },
Если инициализировать данные в `mounted`, то компонент будет создан и срендерен изначально с `null` в качестве данных

2023-10-12 07:26 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-12 07:29 UTC, borshchevsky commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +      </div>
v-if убрал, лишний div удалил.

2023-10-12 07:39 UTC, borshchevsky commented on 07-forms/03-MeetupAgendaItemForm/components/MeetupAgendaItemForm.vue
> +  }
Сделал через localAgendaItem.

2023-10-12 07:59 UTC, borshchevsky commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  }
Исправил.

2023-10-12 08:12 UTC, borshchevsky commented on 07-forms/01-CounterButtonComplete/components/CounterButton.vue
> +  }
Добавил watch: count.

2023-10-12 08:18 UTC, borshchevsky commented on 07-forms/02-MeetupForm/components/MeetupForm.vue
> +    },
Исправил.

2023-10-12 08:18 UTC, borshchevsky commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +      </div>
Исправил.

2023-10-12 08:19 UTC, borshchevsky commented on 07-forms/04-GeneratedForm/components/MeetupAgendaItemForm.vue
> +  },
Исправил на created.

2023-10-12 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-12 08:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-12 08:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-12 10:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 11:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 11:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 13:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 13:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 13:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-12 18:30 UTC, ShGKme reviewed
Исправления приняты

2023-10-12 19:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-12 19:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-13 06:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-13 08:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-13 08:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-10-13 13:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-10-13 20:40 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-10-13 20:43 UTC, merged