tasks
js-tasks-ru/vue-20230905_3410914 pull request #7
Opened 2023-10-23 10:02 UTC by borshchevsky

2023-10-23 10:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-23 16:54 UTC, ShGKme requested changes
Требуется одно маленькое исправление, в целом всё отлично

2023-10-23 16:54 UTC, ShGKme commented on 10-slots/01-UiPaginationView/components/UiPaginationView.vue
>    </div>
Здесь рендерится много контейнеров всей страницы вместо одного контейнера со всеми элементами

2023-10-24 04:57 UTC, borshchevsky commented on 10-slots/01-UiPaginationView/components/UiPaginationView.vue
>    </div>
Исправил.

2023-10-24 04:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-10-24 22:12 UTC, ShGKme approved these changes

2023-10-24 22:13 UTC, merged